[package]
name = "vcdim"
version = "0.1.0"
authors = ["local@localhost <local@localhost>"]

[dependencies]
rand = "0.3"
polygon = { git = "https://github.com/moritzbeck/polygon.git" }

[dev-dependencies]
quick-xml = "0.9.*"

[features]
bench = []
print_info = []
naive_dim = []